### ISSUE TITLE
need little help

### ISSUE THREAD

**Issue by RYG81** [JohannesDeml/UnityWebGL-LoadingTest#1]
Hi,

Can you help me with configuration for IIS server to run WebGL locally?
I know it's not what this repository is for, but may be u know how to do it and can help on this.

Thanks in advance

**Comment by JohannesDeml** [comment]
I never worked with ISS so far, but maybe this guide helps you: https://docs.unity3d.com/Manual/webgl-server-configuration-code-samples.html

**Comment by RYG81** [comment]
I already followed that page with no success. I am getting this error -
Failed to load resource: the server responded with a status of 500 (Internal Server Error) for build.loader.js

have no clue what to do. Still thanks for your time and help.

**Comment by JohannesDeml** [comment]
Hm, other than that I can't really help you. I haven't set it up with ISS so far and also don't have access to an ISS server. I guess the best place to get an answer is the webgl subforum (https://forum.unity.com/forums/webgl.84/).

**Comment by RYG81** [comment]
Today I tried to recreate the website, and it worked. Maybe my good day.
