### ISSUE TITLE
Successful build  but Unity editor crashes causes github actions to fail.

### ISSUE THREAD

**Issue by McSwan** [JohannesDeml/UnityWebGL-LoadingTest#114]
[https://github.com/game-ci/unity-builder/issues/625](url)

Any thoughts on how to fix ?

**Comment by JohannesDeml** [comment]
Is this in any way related to this repo other than your project also using game.ci?

**Comment by McSwan** [comment]
Not really, it looks like your searching for bugs in gameci, and I've found one, if your interested. I suspect opengl core causes the unity editor to crash in webgl in linux in at least 2022.3.12f1+. Cheers - Also if you have any suggestions I'm all ears.

**Comment by JohannesDeml** [comment]
Okay, got it. I will close the ticket, since the GameCI problem does not exist in repo and therefore is not relevant for it.
