### ISSUE TITLE
UPM cannot find nvidia package

### ISSUE THREAD

**Issue by samavan** [JohannesDeml/UnityWebGL-LoadingTest#2]
- From Master
- Unity 2021.1.17f1

From Project first lunch :
![image](https://user-images.githubusercontent.com/6184992/130445879-5db6756d-78e7-4900-aef2-9dcc208a54aa.png)

Once ignored the errors and checking from the UPM window :
![image](https://user-images.githubusercontent.com/6184992/130446107-03f08a65-9a3c-43b6-b23f-1710ca680911.png)

However removing it doesn't affect the project at all and seems to run fine.

**Comment by JohannesDeml** [comment]
I guess this is a package added in the new beta. If you want to test with a non-beta version use the corresponding release (https://github.com/JohannesDeml/UnityWebGL-LoadingTest/releases). I also made some branches for the lts releases, so they also get new functionality. But, yeah, I guess a note somewhere in the readme on what to use would be a good thing. Thanks for bringing it up!

**Comment by samavan** [comment]
Ah I see! Thank you! 🙌
Maybe to commit the project version file may help?

**Comment by JohannesDeml** [comment]
Alrighty, so I took a few steps to avoid those confusions in the future:
* Master has now 2020.3 LTS to have a better default version for people just wanting to use this repo as a basis
* I added some additional info in the readme

The project version is already commited at its [usual place](https://github.com/JohannesDeml/UnityWebGL-LoadingTest/blob/master/ProjectSettings/ProjectVersion.txt), or do you think of something else?

Thanks again for the feedback, I think the changes will help others start off more easily!
