### ISSUE TITLE
Build via "Tools" and .htaccess

### ISSUE THREAD

**Issue by Fenikkel** [JohannesDeml/UnityWebGL-LoadingTest#44]
Hi, first of all, thanks for this open source project. It's fucking incredible. I learned a lot thanks to you!

There is no difference between build via your plugin (Tools/Build WebGL) and BuildStettins/Build if you do the same configurations right? (Of course your plugin makes easier do the builds)

If we want to upload the game in Github pages or similar, we need to take into account the [.htaccess](https://github.com/JohannesDeml/UnityWebGL-LoadingTest/blob/master/Configuration/2020/.htaccess)? I made a lot of successful attempts and there was no need of this file. I don't know where it goes. I suppose that matters if you have access to the server?

Thanks in advance,
Pau

**Comment by JohannesDeml** [comment]
Hi Fenikkel,

> It's fucking incredible. I learned a lot thanks to you!

Cheers, glad you like it!
Yes, there is no difference between building through the Tools Menu Item and the normal build settings, it just makes switching stuff easier (and in my case where I want to compare quite a few different settings, it is nice to run it in the editor and through CI with the same settings).

> If we want to upload the game in Github pages or similar, we need to take into account the [.htaccess](https://github.com/JohannesDeml/UnityWebGL-LoadingTest/blob/master/Configuration/2020/.htaccess)? I made a lot of successful attempts and there was no need of this file. I don't know where it goes. I suppose that matters if you have access to the server?

If it works, then there is no need to upload it. The .htaccess file provided in this repo is also for a very specific server type (litespeed), most servers have an apache or nginx running, the htaccess files for those can be found in the [unity documentation](https://docs.unity3d.com/Manual/webgl-server-configuration-code-samples.html). And exactly as you said, this is mostly for when you have access to the server and need to configure it properly. This is mostly relevant when you use brotli or gzip compression.
