### ISSUE TITLE
 ios running webgl performance problem

### ISSUE THREAD

**Issue by zhaorui-creator** [JohannesDeml/UnityWebGL-LoadingTest#73]
Hello, I would like to ask the webgl exported from the example project to deploy and run on ios after the CPU usage is very high and heat up, but it will not run on ios using the demo given in the warehouse.

**Comment by JohannesDeml** [comment]
Hey there!

Did I get you right, that you're asking for the builds that I deployed on my server? If so, you can find them in the releases (e.g. https://github.com/JohannesDeml/UnityWebGL-LoadingTest/releases/tag/1.1.0) as attached assets. Note on the builds: They are all compressed with brotli, so you will need to configure your server correctly to serve this file format (this is different from server to server, see also [Notes](https://github.com/JohannesDeml/UnityWebGL-LoadingTest#notes)).
You can also easily build the project yourself with the version you want to test (I have a branch for each major unity version, easiest would be to pick the one you want to test).

If you only want to test different unity versions with your iOS device, you can do so on the following website: https://deml.io/experiments/unity-webgl/
On my iPhone SE 2020 they run quite fine (development builds take a lot longer to load, but that is expected), without heating up too much.

If this doesn't answer your question, could you please clarify what exactly you are looking for? :)

**Comment by zhaorui-creator** [comment]
I use you own export webgl engineering, their deployment to the server, and then the CPU use ios devices running high, fever, but found no use your builds on  https://deml.io/experiments/unity-webgl/ with very high CPU load. So I don't know if my export build parameters have errors or if I need to select decelopment buld

**Comment by JohannesDeml** [comment]
Are you deploying this project to your server? Then I would be surprised, if the CPU load on the device is a lot higher. You can verify, that your build settings are the problem, by using the the build export menu from my project, just run Tools->Build WebGL->webgl2
![image](https://github.com/JohannesDeml/UnityWebGL-LoadingTest/assets/4518980/f9025f8c-af61-4a13-9e0c-dbde03d5bfc5)

You can also download one of the builds from the releases, and deploy them on your server to see if there are any problems with your server configuration - Make sure your configuration allows for brotli compression.

**Comment by zhaorui-creator** [comment]
Thank you! very much! I made a mistake in the settings before, and now it's fixed

**Comment by JohannesDeml** [comment]
Cool, glad it got resolved :)
