### ISSUE TITLE
Build weight is heavier than expected.

### ISSUE THREAD

**Issue by pyscriptbug** [JohannesDeml/UnityWebGL-LoadingTest#89]
Hello @JohannesDeml !

I'm cloning your repo and using the `2023.1-urp` branch to create a build. I'm upgrading to `2023.1.18f1` and upgrading packages to their latest version.

I'm changing the Build Target to WebGL and using the `webgl2` build tool that is added to the toolbar. Literally changing nothing to the project other than upgrading stuff.

But the result is way heavier that what you have. You can see the reference to the data.br and wasm.br files.

What am I doing wrong?

I'm on MacOS Monterey 12.6 and using the `Intel` version of unity editor

<img width="484" alt="image" src="https://github.com/JohannesDeml/UnityWebGL-LoadingTest/assets/30703501/85f4c9c2-767a-4807-b86c-0b3c06566fa0">

<img width="471" alt="image" src="https://github.com/JohannesDeml/UnityWebGL-LoadingTest/assets/30703501/bfb07b1f-ed9a-450a-831e-b97e883778bc">

**Comment by JohannesDeml** [comment]
Hi @pyscriptbug!

URP is ~3 MB larger than a builtin renderpipeline build. Sadly the automated URP builds for 2023.1 are failing for me (see https://github.com/game-ci/docker/issues/214), therefore I don't have any numbers of the current build size for that version. If you have a look at all the live builds, you can see the size for webgl1, webgl2 with and without urp to get an idea. 

What comes closest to your build is [2022.3.10f1-urp-webgl2 (5.81 MB)](https://deml.io/experiments/unity-webgl/2022.3.10f1-urp-webgl2) - With 5.81 MB this is still quite a bit smaller than your build, but I could imagine that this comes from new features in the URP package. I will do a local build to see at which size I'm ending up, but I could imagine that you're doing nothing wrong and this is just the size of 2023.1 with urp.

**Comment by pyscriptbug** [comment]
Thank you for your response @JohannesDeml!

That makes a lot of sense, I was comparing my build size to your built-in example. Even if it's a little bit heavier than the one you've provided it might be because of some new features added to URP in the latest version.

**Comment by JohannesDeml** [comment]
For completeness, here is the local build I made: [2023.1.18f1-webgl2-manualBuild (6.22 MB)](https://deml.io/experiments/unity-webgl/2023.1.18f1-webgl2-manualBuild)

This matches your build size quite well :)
![image](https://github.com/JohannesDeml/UnityWebGL-LoadingTest/assets/4518980/60725713-f85c-4bbb-867d-ce6d2351354b)

**Comment by JohannesDeml** [comment]
Oh, I forgot to mention. You can also build for min size (I added a menu command for that in the project)
![image](https://github.com/JohannesDeml/UnityWebGL-LoadingTest/assets/4518980/d780cb12-1283-4fcf-ab66-47770a195cfa)

Then the build ends up being almost one MB smaller: [2023.1.18f1-minsize-webgl1-manualBuild (5.37 MB)](https://deml.io/experiments/unity-webgl/2023.1.18f1-minsize-webgl1-manualBuild)

**Comment by pyscriptbug** [comment]
Awesome, thank you!
